namespace TradingView.DAL.Entities;

public class FundamentalsData
{
    public long AccountsPayable { get; set; }

    public int AccountsPayableTurnover { get; set; }

    public long AccountsReceivable { get; set; }
    public int AccountsReceivableTurnover { get; set; }
    public string? AsOfDate { get; set; }
    public long AssetsCurrentCash { get; set; }
    public int AssetsCurrentCashRestricted { get; set; }
    public int AssetsCurrentDeferredCompensation { get; set; }
    public int AssetsCurrentDeferredTax { get; set; }
    public long AssetsCurrentDiscontinuedOperations { get; set; }
    public long AssetsCurrentInvestments { get; set; }
    public int AssetsCurrentLeasesOperating { get; set; }
    public long AssetsCurrentLoansNet { get; set; }
    public long AssetsCurrentOther { get; set; }
    public int AssetsCurrentSeparateAccounts { get; set; }
    public long AssetsCurrentUnadjusted { get; set; }
    public long AssetsFixed { get; set; }
    public int AssetsFixedDeferredCompensation { get; set; }
    public long AssetsFixedDeferredTax { get; set; }
    public int AssetsFixedDiscontinuedOperations { get; set; }
    public int AssetsFixedLeasesOperating { get; set; }
    public int AssetsFixedOperatingDiscontinuedOperations { get; set; }
    public long AssetsFixedOperatingSubsidiaryUnconsolidated { get; set; }
    public int AssetsFixedOreo { get; set; }
    public long AssetsFixedOther { get; set; }
    public int AssetsFixedUnconsolidated { get; set; }
    public long AssetsUnadjusted { get; set; }
    public long Capex { get; set; }
    public long CapexAcquisition { get; set; }
    public int CapexMaintenance { get; set; }
    public int CashConversionCycle { get; set; }
    public long CashFlowFinancing { get; set; }
    public long CashFlowInvesting { get; set; }
    public long CashFlowOperating { get; set; }
    public int CashFlowShareRepurchase { get; set; }
    public int CashLongTerm { get; set; }
    public long CashOperating { get; set; }
    public int CashPaidForIncomeTaxes { get; set; }
    public int CashPaidForInterest { get; set; }
    public int CashRestricted { get; set; }
    public int ChargeAfterTax { get; set; }
    public int ChargeAfterTaxDiscontinuedOperations { get; set; }
    public int ChargesAfterTaxOther { get; set; }
    public string? Cik { get; set; }
    public int CreditLossProvision { get; set; }
    public string? DataGenerationDate { get; set; }
    public int DaysInAccountsPayable { get; set; }
    public int DaysInInventory { get; set; }
    public int DaysInRevenueDeferred { get; set; }
    public int DaysRevenueOutstanding { get; set; }
    public long DebtFinancial { get; set; }
    public int DebtShortTerm { get; set; }
    public long DepreciationAndAmortizationAccumulated { get; set; }
    public long DepreciationAndAmortizationCashFlow { get; set; }
    public int DividendsPreferred { get; set; }
    public int DividendsPreferredRedeemableMandatorily { get; set; }
    public long EarningsRetained { get; set; }
    public int EbitReported { get; set; }
    public long EbitdaReported { get; set; }
    public long EquityShareholder { get; set; }
    public int EquityShareholderOther { get; set; }
    public int EquityShareholderOtherDeferredCompensation { get; set; }
    public int EquityShareholderOtherEquity { get; set; }
    public int EquityShareholderOtherMezzanine { get; set; }
    public long Expenses { get; set; }
    public int ExpensesAcquisitionMerger { get; set; }
    public int ExpensesCompensation { get; set; }
    public int ExpensesDepreciationAndAmortization { get; set; }
    public int ExpensesDerivative { get; set; }
    public int ExpensesDiscontinuedOperations { get; set; }
    public int ExpensesDiscontinuedOperationsReits { get; set; }
    public int ExpensesEnergy { get; set; }
    public int ExpensesForeignCurrency { get; set; }
    public int ExpensesInterest { get; set; }
    public int ExpensesInterestFinancials { get; set; }
    public int ExpensesInterestMinority { get; set; }
    public int ExpensesLegalRegulatoryInsurance { get; set; }
    public int ExpensesNonOperatingCompanyDefinedOther { get; set; }
    public int ExpensesNonOperatingOther { get; set; }
    public int ExpensesNonOperatingSubsidiaryUnconsolidated { get; set; }
    public int ExpensesNonRecurringOther { get; set; }
    public long ExpensesOperating { get; set; }
    public long ExpensesOperatingOther { get; set; }
    public int ExpensesOperatingSubsidiaryUnconsolidated { get; set; }
    public int ExpensesOreo { get; set; }
    public int ExpensesOreoReits { get; set; }
    public int ExpensesOtherFinancing { get; set; }
    public int ExpensesRestructuring { get; set; }
    public long ExpensesSga { get; set; }
    public int ExpensesStockCompensation { get; set; }
    public int ExpensesWriteDown { get; set; }
    public int Ffo { get; set; }
    public string? Figi { get; set; }
    public string? FilingDate { get; set; }
    public string? FilingType { get; set; }
    public int FiscalQuarter { get; set; }
    public int FiscalYear { get; set; }
    public int GoodwillAmortizationCashFlow { get; set; }
    public int GoodwillAmortizationIncomeStatement { get; set; }
    public int GoodwillAndIntangiblesNetOther { get; set; }
    public int GoodwillNet { get; set; }
    public int IncomeFromOperations { get; set; }
    public int IncomeNet { get; set; }
    public int IncomeNetPerRevenue { get; set; }
    public int IncomeNetPerWabso { get; set; }
    public int IncomeNetPerWabsoSplitAdjusted { get; set; }
    public int IncomeNetPerWabsoSplitAdjustedYoyDeltaPercent { get; set; }
    public int IncomeNetPerWadso { get; set; }
    public int IncomeNetPerWadsoSplitAdjusted { get; set; }
    public int IncomeNetPerWadsoSplitAdjustedYoyDeltaPercent { get; set; }
    public int IncomeNetPreTax { get; set; }
    public long IncomeNetYoyDelta { get; set; }
    public int IncomeOperating { get; set; }
    public int IncomeOperatingDiscontinuedOperations { get; set; }
    public int IncomeOperatingOther { get; set; }
    public int IncomeOperatingSubsidiaryUnconsolidated { get; set; }
    public int IncomeOperatingSubsidiaryUnconsolidatedAfterTax { get; set; }
    public int IncomeTax { get; set; }
    public int IncomeTaxCurrent { get; set; }
    public int IncomeTaxDeferred { get; set; }
    public int IncomeTaxDiscontinuedOperations { get; set; }
    public int IncomeTaxOther { get; set; }
    public int IncomeTaxRate { get; set; }
    public int InterestMinority { get; set; }
    public long Inventory { get; set; }
    public int InventoryTurnover { get; set; }
    public long Liabilities { get; set; }
    public long LiabilitiesCurrent { get; set; }
    public long LiabilitiesNonCurrentAndInterestMinorityTotal { get; set; }
    public long LiabilitiesNonCurrentDebt { get; set; }
    public int LiabilitiesNonCurrentDeferredCompensation { get; set; }
    public int LiabilitiesNonCurrentDeferredTax { get; set; }
    public int LiabilitiesNonCurrentDiscontinuedOperations { get; set; }
    public int LiabilitiesNonCurrentLeasesOperating { get; set; }
    public long LiabilitiesNonCurrentLongTerm { get; set; }
    public int LiabilitiesNonCurrentOperatingDiscontinuedOperations { get; set; }
    public long LiabilitiesNonCurrentOther { get; set; }
    public int NibclDeferredCompensation { get; set; }
    public int NibclDeferredTax { get; set; }
    public int NibclDiscontinuedOperations { get; set; }
    public int NibclLeasesOperating { get; set; }
    public long NibclOther { get; set; }
    public int NibclRestructuring { get; set; }
    public int NibclRevenueDeferred { get; set; }
    public int NibclRevenueDeferredTurnover { get; set; }
    public int NibclSeparateAccounts { get; set; }
    public long Oci { get; set; }
    public string? PeriodEndDate { get; set; }
    public long PpAndENet { get; set; }
    public int PricePerEarnings { get; set; }
    public int PricePerEarningsPerRevenueYoyDeltaPercent { get; set; }
    public long ProfitGross { get; set; }
    public int ProfitGrossPerRevenue { get; set; }
    public int ResearchAndDevelopmentExpense { get; set; }
    public int Reserves { get; set; }
    public int ReservesInventory { get; set; }
    public int ReservesLifo { get; set; }
    public int ReservesLoanLoss { get; set; }
    public long Revenue { get; set; }
    public long RevenueCostOther { get; set; }
    public int RevenueIncomeInterest { get; set; }
    public long RevenueOther { get; set; }
    public int RevenueSubsidiaryUnconsolidated { get; set; }
    public long SalesCost { get; set; }
    public long SharesIssued { get; set; }
    public int SharesOutstandingPeDateBs { get; set; }
    public int SharesTreasury { get; set; }
    public long StockCommon { get; set; }
    public int StockPreferred { get; set; }
    public int StockPreferredEquity { get; set; }
    public int StockPreferredMezzanine { get; set; }
    public int StockTreasury { get; set; }
    public string? Symbol { get; set; }
    public long Wabso { get; set; }
    public long WabsoSplitAdjusted { get; set; }
    public long Wadso { get; set; }
    public long WadsoSplitAdjusted { get; set; }
    public string? Id { get; set; }
    public string? Key { get; set; }
    public string? Subkey { get; set; }
    public long Date { get; set; }
    public long Updated { get; set; }
}
