namespace TradingView.DAL.Entities.StockFundamentals;
public class ReportedFinancials
{
    public double? AccountsPayableCurrent { get; set; }
    public double? AccountsReceivableNetCurrent { get; set; }
    public double? AccruedIncomeTaxesCurrent { get; set; }
    public double? AccruedIncomeTaxesNoncurrent { get; set; }
    public double? AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment { get; set; }
    public double? AccumulatedOtherComprehensiveIncomeLossNetOfTax { get; set; }
    public double? AcquisitionsNetofCashAcquiredAndPurchasesOfIntangibleandOtherAssets { get; set; }
    public double? AllocatedShareBasedCompensationExpense { get; set; }
    public double? AllowanceForDoubtfulAccountsReceivableCurrent { get; set; }
    public double? AmortizationOfIntangibleAssets { get; set; }
    public double? Assets { get; set; }
    public double? AssetsCurrent { get; set; }
    public double? AssetsFairValueDisclosureRecurring { get; set; }
    public double? AvailableForSaleDebtSecuritiesAmortizedCostBasis { get; set; }
    public double? AvailableForSaleSecurities { get; set; }
    public double? AvailableForSaleSecuritiesAccumulatedGrossUnrealizedGainBeforeTax { get; set; }
    public double? AvailableForSaleSecuritiesAccumulatedGrossUnrealizedLossBeforeTax { get; set; }
    public double? AvailableForSaleSecuritiesAmortizedCost { get; set; }
    public double? AvailableForSaleSecuritiesContinuousUnrealizedLossPosition12MonthsOrLongerAccumulatedLoss { get; set; }
    public double? AvailableForSaleSecuritiesContinuousUnrealizedLossPositionAccumulatedLoss { get; set; }
    public double? AvailableForSaleSecuritiesContinuousUnrealizedLossPositionFairValue { get; set; }
    public double? AvailableForSaleSecuritiesContinuousUnrealizedLossPositionLessThan12MonthsAccumulatedLoss { get; set; }
    public double? AvailableForSaleSecuritiesContinuousUnrealizedLossPositionLessThanTwelveMonthsFairValue { get; set; }
    public double? AvailableForSaleSecuritiesContinuousUnrealizedLossPositionTwelveMonthsOrLongerFairValue { get; set; }
    public double? AvailableForSaleSecuritiesCurrent { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsAmortizedCostBasis { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesNextRollingTwelveMonthsFairValue { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenAmortizedCostBasis { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesRollingAfterYearTenFairValue { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenAmortizedCostBasis { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesRollingYearSixThroughTenFairValue { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveAmortizedCostBasis { get; set; }
    public double? AvailableForSaleSecuritiesDebtMaturitiesRollingYearTwoThroughFiveFairValue { get; set; }
    public double? AvailableForSaleSecuritiesDebtSecurities { get; set; }
    public double? AvailableForSaleSecuritiesGrossRealizedGains { get; set; }
    public double? AvailableForSaleSecuritiesGrossRealizedLosses { get; set; }
    public double? BusinessCombinationIntegrationRelatedCosts { get; set; }
    public double? CapitalizedComputerSoftwareAmortization { get; set; }
    public double? CashAndCashEquivalentsAtCarryingValue { get; set; }
    public double? CashAndCashEquivalentsPeriodIncreaseDecrease { get; set; }
    public double? CashCashEquivalentsAndShortTermInvestments { get; set; }
    public double? CommercialPaper { get; set; }
    public double? CommitmentAmountUponClosingMergerTransaction { get; set; }
    public double? CommonStockDividendsPerShareDeclared { get; set; }
    public double? CommonStockSharesAuthorized { get; set; }
    public double? CommonStockSharesOutstanding { get; set; }
    public double? CommonStocksIncludingAdditionalPaidInCapital { get; set; }
    public double? ComprehensiveIncomeNetOfTax { get; set; }
    public double? CostOfRevenue { get; set; }
    public double? DebtInstrumentFaceAmount { get; set; }
    public double? DebtInstrumentUnamortizedDiscount { get; set; }
    public double? DebtLongtermAndShorttermCombinedAmount { get; set; }
    public double? DeferredIncomeTaxExpenseBenefit { get; set; }
    public double? DeferredRevenue { get; set; }
    public double? DeferredRevenueCurrent { get; set; }
    public double? DeferredRevenueNoncurrent { get; set; }
    public double? DeferredTaxAssetsLiabilitiesNetCurrent { get; set; }
    public double? DeferredTaxLiabilitiesNoncurrent { get; set; }
    public double? DepositsReceivedForSecuritiesLoanedAtCarryingValue { get; set; }
    public double? DepreciationAmortizationAndOther { get; set; }
    public double? DerivativeInstrumentsNotDesignatedAsHedgingInstrumentsGainLossNet { get; set; }
    public DateTime? DividendPayableDateToBePaidDayMonthAndYear { get; set; }
    public double? DividendsCommonStockCash { get; set; }
    public DateTime? DividendsPayableDateDeclaredDayMonthAndYear { get; set; }
    public DateTime? DividendsPayableDateOfRecordDayMonthAndYear { get; set; }
    public string? DocumentFiscalPeriodFocus { get; set; }
    public int? DocumentFiscalYearFocus { get; set; }
    public string? DocumentType { get; set; }
    public double? EarningsPerShareBasic { get; set; }
    public double? EarningsPerShareDiluted { get; set; }
    public double? EffectOfExchangeRateOnCashAndCashEquivalents { get; set; }
    public double? EffectiveIncomeTaxRateContinuingOperations { get; set; }
    public double? EmployeeRelatedLiabilitiesCurrent { get; set; }
    public double? ExcessTaxBenefitFromShareBasedCompensationFinancingActivities { get; set; }
    public double? ExcessTaxBenefitFromShareBasedCompensationOperatingActivities { get; set; }
    public double? FiniteLivedIntangibleAssetsAccumulatedAmortization { get; set; }
    public double? FiniteLivedIntangibleAssetsAmortizationExpenseAfterYearFive { get; set; }
    public double? FiniteLivedIntangibleAssetsAmortizationExpenseRemainderOfFiscalYear { get; set; }
    public double? FiniteLivedIntangibleAssetsAmortizationExpenseYearFive { get; set; }
    public double? FiniteLivedIntangibleAssetsAmortizationExpenseYearFour { get; set; }
    public double? FiniteLivedIntangibleAssetsAmortizationExpenseYearThree { get; set; }
    public double? FiniteLivedIntangibleAssetsAmortizationExpenseYearTwo { get; set; }
    public double? FiniteLivedIntangibleAssetsGross { get; set; }
    public double? FiniteLivedIntangibleAssetsNet { get; set; }
    public double? ForeignCurrencyCashFlowHedgeGainLossToBeReclassifiedDuringNext12Months { get; set; }
    public double? ForeignCurrencyTransactionGainLossBeforeTax { get; set; }
    public double? GainLossOnInvestments { get; set; }
    public double? GainLossOnInvestmentsAndDerivativeInstruments { get; set; }
    public double? GeneralAndAdministrativeExpense { get; set; }
    public double? Goodwill { get; set; }
    public double? GrossProfit { get; set; }
    public double? HeldToMaturitySecurities { get; set; }
    public double? HeldToMaturitySecuritiesAccumulatedUnrecognizedHoldingGain { get; set; }
    public double? HeldToMaturitySecuritiesAmortizedCostBeforeOtherThanTemporaryImpairment { get; set; }
    public double? HeldToMaturitySecuritiesFairValue { get; set; }
    public double? IncomeLossFromContinuingOperationsBeforeIncomeTaxesMinorityInterestAndIncomeLossFromEquityMethodInvestments { get; set; }
    public double? IncomeTaxExpenseBenefit { get; set; }
    public double? IncreaseDecreaseInAccountsPayable { get; set; }
    public double? IncreaseDecreaseInAccountsReceivable { get; set; }
    public double? IncreaseDecreaseInCollateralHeldUnderSecuritiesLending { get; set; }
    public double? IncreaseDecreaseInDeferredRevenue { get; set; }
    public double? IncreaseDecreaseInInventories { get; set; }
    public double? IncreaseDecreaseInOtherCurrentAssets { get; set; }
    public double? IncreaseDecreaseInOtherCurrentLiabilities { get; set; }
    public double? IncreaseDecreaseInOtherNoncurrentAssets { get; set; }
    public double? IncreaseDecreaseInOtherNoncurrentLiabilities { get; set; }
    public double? IncrementalCommonSharesAttributableToShareBasedPaymentArrangements { get; set; }
    public double? InterestExpense { get; set; }
    public double? InventoryFinishedGoodsNetOfReserves { get; set; }
    public double? InventoryNet { get; set; }
    public double? InventoryRawMaterialsNetOfReserves { get; set; }
    public double? InventoryWorkInProcessNetOfReserves { get; set; }
    public double? InvestmentIncomeNet { get; set; }
    public double? Liabilities { get; set; }
    public double? LiabilitiesAndStockholdersEquity { get; set; }
    public double? LiabilitiesCurrent { get; set; }
    public double? LongTermDebt { get; set; }
    public double? LongTermDebtCurrent { get; set; }
    public double? LongTermDebtFairValue { get; set; }
    public double? LongTermDebtNoncurrent { get; set; }
    public double? LongTermInvestments { get; set; }
    public double? LongTermInvestmentsExcludingHeldToMaturity { get; set; }
    public double? MarketableSecuritiesRealizedGainLossOtherThanTemporaryImpairmentsAmount { get; set; }
    public double? NetCashProvidedByUsedInFinancingActivitiesContinuingOperations { get; set; }
    public double? NetCashProvidedByUsedInInvestingActivitiesContinuingOperations { get; set; }
    public double? NetCashProvidedByUsedInOperatingActivitiesContinuingOperations { get; set; }
    public double? NetIncomeLoss { get; set; }
    public double? NoncashAssetRelatedRestructuringCharge { get; set; }
    public double? NonoperatingIncomeExpense { get; set; }
    public double? OperatingExpenses { get; set; }
    public double? OperatingIncomeLoss { get; set; }
    public double? OtherAssetsCurrent { get; set; }
    public double? OtherAssetsFairValueDisclosure { get; set; }
    public double? OtherAssetsNoncurrent { get; set; }
    public double? OtherComprehensiveIncomeLossAvailableForSaleSecuritiesAdjustmentNetOfTax { get; set; }
    public double? OtherComprehensiveIncomeLossAvailableForSaleSecuritiesTax { get; set; }
    public double? OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesNetOfTax { get; set; }
    public double? OtherComprehensiveIncomeLossDerivativesQualifyingAsHedgesTax { get; set; }
    public double? OtherComprehensiveIncomeLossForeignCurrencyTransactionAndTranslationAdjustmentNetOfTax { get; set; }
    public double? OtherComprehensiveIncomeLossForeignCurrencyTranslationAdjustmentTax { get; set; }
    public double? OtherComprehensiveIncomeLossNetOfTax { get; set; }
    public double? OtherFinancialInstrumentCovenantMinimumLiquidity { get; set; }
    public double? OtherLiabilitiesCurrent { get; set; }
    public double? OtherLiabilitiesNoncurrent { get; set; }
    public double? OtherNonoperatingIncomeExpense { get; set; }
    public double? PaymentsForRepurchaseOfCommonStock { get; set; }
    public double? PaymentsOfDividendsCommonStock { get; set; }
    public double? PaymentsToAcquireInvestments { get; set; }
    public double? PaymentsToAcquirePropertyPlantAndEquipment { get; set; }
    public double? ProceedsFromDebtMaturingInMoreThanThreeMonths { get; set; }
    public double? ProceedsFromIssuanceOfCommonStock { get; set; }
    public double? ProceedsFromMaturitiesPrepaymentsAndCallsOfAvailableForSaleSecurities { get; set; }
    public double? ProceedsFromPaymentsForOtherFinancingActivities { get; set; }
    public double? ProceedsFromRepaymentsOfShortTermDebtMaturingInThreeMonthsOrLess { get; set; }
    public double? ProceedsFromSaleOfAvailableForSaleSecurities { get; set; }
    public double? PropertyPlantAndEquipmentNet { get; set; }
    public double? RecognitionOfDeferredRevenue { get; set; }
    public int? RepaymentsOfDebtMaturingInMoreThanThreeMonths { get; set; }
    public double? ResearchAndDevelopmentExpense { get; set; }
    public double? RestructuringAndRelatedCostExpectedCostRemaining1 { get; set; }
    public double? RestructuringAndRelatedCostNumberOfPositionsEliminatedInceptionToDate { get; set; }
    public double? RestructuringCharges { get; set; }
    public double? RestructuringReserve { get; set; }
    public double? RetainedEarningsAccumulatedDeficit { get; set; }
    public double? SalesRevenueNet { get; set; }
    public double? SecuritiesLoaned { get; set; }
    public double? SegmentOperatingExpenseExcludingIntegrationAndRestructuring { get; set; }
    public double? SellingAndMarketingExpense { get; set; }
    public double? ShortTermBorrowings { get; set; }
    public double? StockRepurchaseProgramRemainingAuthorizedRepurchaseAmount1 { get; set; }
    public double? StockholdersEquity { get; set; }
    public string? TradingSymbol { get; set; }
    public double? WeightedAverageNumberOfDilutedSharesOutstanding { get; set; }
    public double? WeightedAverageNumberOfSharesOutstandingBasic { get; set; }
    public string? AccessionNumber { get; set; }
    public string? Cik { get; set; }
    public long? Date { get; set; }
    public long? DateFiled { get; set; }
    // public string? documentType { get; set; }
    public string? EntityName { get; set; }
    public string? Id { get; set; }
    public string? IrsNumber { get; set; }
    public string? Key { get; set; }
    public long? PeriodEnd { get; set; }
    public long? PeriodStart { get; set; }
    public string? ReportLink { get; set; }
    public string? Subkey { get; set; }
    public string? Update { get; set; }
    public long? Updated { get; set; }
}
